color 8
cls

::Backs up Documents
 xcopy "G:\Gitstuff\TarlabTechnologies\Flags" "E:\Kerbal Space Program (DEV)\GameData\TarlabTechnologies\Flags" /m/e/h/i/v/r/y
 xcopy "G:\Gitstuff\TarlabTechnologies\Parts" "E:\Kerbal Space Program (DEV)\GameData\TarlabTechnologies\Parts" /m/e/h/i/v/r/y
 xcopy "G:\Gitstuff\TarlabTechnologies\Plugins" "E:\Kerbal Space Program (DEV)\GameData\TarlabTechnologies\Plugins" /m/e/h/i/v/r/y
 xcopy "G:\Gitstuff\TarlabTechnologies\Textures" "E:\Kerbal Space Program (DEV)\GameData\TarlabTechnologies\Textures" /m/e/h/i/v/r/y

::Exits
 pause
 exit

